# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.20
    ports:
      - 9411:9411

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: metrics-amd64:1.0
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API

  # This is the core CRUD based service.
  sales-api:
    container_name: sales-api
    networks:
      - shared-network
    image: sales-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    environment:
      - GODEBUG=gctrace=1
    depends_on:
      - metrics
      - zipkin
